#!/usr/bin/env bash
# Installs, configures, and starts the server
#!/bin/bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx redirection
echo "Hello World!" | sudo tee /var/www/html/index.html

replacement_string="server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=AJN9uU35VVs permanent;"

sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
